#! /usr/bin/env sh
usage()
{
cat << EOF

USAGE:     haploclique-assembly-auto options...

OPTIONS:
   -h      Show this message
   -r      Path to the reference genome (required)
   -i      Path to the alignment in BAM format (required)
   -l      Whole genome coverage is below 1000x
   -a      PacBio single amplicon mode

UPDATE:    http://bit.ly/haploclique
EOF
}

REF=
ALIGNMENT=
LOW=0
AMPLICON=0
while getopts “h:r:i:la” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         a)
             AMPLICON=1
             ;;
         r)
             REF=$OPTARG
             ;;
         i)
             ALIGNMENT=$OPTARG
             ;;
         l)
             LOW=1
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

if [[ -z $REF ]] || [[ -z $ALIGNMENT ]]
then
     usage
     exit 1
fi

if [[ $AMPLICON == 1 ]] && [[ $LOW == 1 ]]
then
	echo "Amplicon mode -a cannot be used with -l"
	exit 1
fi

if [[ $LOW == 1 ]] && [[ $AMPLICON == 0 ]] 
then
haploclique-assembly -r $REF -c 1000 -z 250 -x 250 -i $ALIGNMENT -t 2
haploclique-assembly -r $REF -c 1000 -z 500 -x 300 -i $ALIGNMENT -t 2
haploclique-assembly -r $REF -c 1000 -z 500 -x 400 -i $ALIGNMENT -t 2
haploclique-assembly -r $REF -c 1000 -z 500 -x 500 -i $ALIGNMENT -t 2
haploclique-assembly -r $REF -c 1000 -z 750 -x 750 -i $ALIGNMENT -t 2
haploclique-assembly -r $REF -c 1000 -z 1000 -x 1000 -i $ALIGNMENT -t 7
haploclique-assembly -r $REF -c 1000 -z 1000 -i $ALIGNMENT -o 0.8 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 1000 -z 1000 -i $ALIGNMENT -o 0.7 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 1000 -z 1000 -i $ALIGNMENT -o 0.6 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -z 1000 -i $ALIGNMENT -o 300 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -z 1000 -i $ALIGNMENT -o 250 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -z 1000 -i $ALIGNMENT -o 200 -q 0.999 -t 5 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -G -i $ALIGNMENT -o 0.8 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -G -i $ALIGNMENT -o 0.7 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -G -i $ALIGNMENT -o 0.6 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -G -i $ALIGNMENT -o 300 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -G -i $ALIGNMENT -o 250 -q 0.999 -t 2 -n -w -s 1
haploclique-assembly -r $REF -c 2000 -G -i $ALIGNMENT -o 200 -q 0.999 -t 2 -n -w -s 1
fi
if [[ $LOW == 0 ]] && [[ $AMPLICON == 0 ]]
then
	haploclique-assembly -r $REF -c 1000 -z 250 -i $ALIGNMENT -t 5 -o 0.9 -j 0.9
	haploclique-assembly -r $REF -c 1000 -z 500 -i $ALIGNMENT -t 2 -o 0.9 -j 0.9
    haploclique-assembly -r $REF -c 1000 -z 250 -i $ALIGNMENT -o 0.8 -q 0.999 -t 2 -j 0.9 -n -w -s 1
    haploclique-assembly -r $REF -c 1000 -z 500 -i $ALIGNMENT -o 0.8 -q 0.999 -t 2 -j 0.9 -n -w -s 1
    haploclique-assembly -r $REF -c 1000 -z 500 -i $ALIGNMENT -o 0.7 -q 0.999 -t 2 -j 0.9 -n -w -s 1
    haploclique-assembly -r $REF -c 1000 -z 500 -i $ALIGNMENT -o 0.6 -q 0.999 -t 2 -j 0.9 -n -w -s 1
    haploclique-assembly -r $REF -c 1000 -z 500 -i $ALIGNMENT -o 500 -q 0.999 -t 2 -j 0.9 -n -w -s 1
    haploclique-assembly -r $REF -c 1000 -z 500 -i $ALIGNMENT -o 400 -q 0.999 -t 2 -j 0.9 -n -w -s 1
    haploclique-assembly -r $REF -c 1000 -z 500 -i $ALIGNMENT -o 300 -q 0.999 -t 2 -j 0.9 -n -w -s 1
    haploclique-assembly -r $REF -c 1000 -z 500 -i $ALIGNMENT -o 200 -q 0.999 -t 2 -j 0.9 -n -w -s 1
fi

if [[ $AMPLICON == 1 ]]
then
    haploclique-assembly -i $ALIGNMENT -r $REF -z 50 -p -c 1000 -x 100
    haploclique-assembly -i $ALIGNMENT -r $REF -z 100 -p -c 1000 -x 150 -u
    haploclique-assembly -i $ALIGNMENT -r $REF -z 150 -p -c 1000 -x 200 -u
    haploclique-assembly -i $ALIGNMENT -r $REF -z 200 -p -c 1000 -x 250 -u
    cat singles.prior >> alignment.prior
    haploclique-assembly -i $ALIGNMENT -r $REF -G -e -p -t 2
fi